<?php

namespace App\Filament\Resources\EnvironmentResource\Pages;

use App\Filament\Resources\EnvironmentResource;
use Filament\Actions;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Form;
use Filament\Resources\Pages\EditRecord;


class EditEnvironment extends EditRecord
{
    protected static string $resource = EnvironmentResource::class;
    protected static ?string $title = 'Manage Environment';
    protected static ?string $breadcrumb = 'Manage Environment';


//    protected static string $view = 'filament.resources.environments.pages.edit-environment';

    public function hasCombinedRelationManagerTabsWithContent(): bool
    {
        return true;
    }

    public function getContentTabLabel(): ?string
    {
        // overriding the parent method
        return 'Environment';
    }

    protected function getForms(): array
    {
        return parent::getForms(); // TODO: Change the autogenerated stub
    }

    public $stupidness = 'doobas';

    protected function getHeaderActions(): array
    {
        return [
//            Actions\ViewAction::make(),
            Actions\DeleteAction::make(),
        ];
    }


}
